// eslint-disable-next-line import/prefer-default-export
export enum Channels {
  LOADED = 'loaded',
  CONFIG_CHANGED = 'config-changed',
  STOP_PROJECT = 'stop-project',
  START_PROJECT = 'start-project',
  STATE_CHANGED = 'state-changed',
  SHOW_ERROR = 'show-error',
  SHOW_INFO = 'show-info',
  SHOW_WARNING = 'show-warning',
  SHOW_SUCCESS = 'show-success',
  TRAFFIC_DATA = 'traffic-data',
  EDIT_PROJECT = 'edit-project',
  UPDATE_OR_CREATE_PROJECT = 'update-or-create-project',
  DELETE_PROJECT = 'delete-project',
  REQUEST_ANSWER = 'request-answer',
  REQUEST_GET_NAMESPACES = 'request-get-namespaces',
  REQUEST_GET_CONTEXTS = 'request-get-contexts',
  REQUEST_GET_PODS = 'request-get-pods',
  SHOW_ALERT = 'show-alert',
}
